# Generated by Django 4.2.7 on 2023-11-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
            ],
            options={
                'verbose_name': 'Client Coupon',
                'verbose_name_plural': 'Client Coupons',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.coupon',),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
            ],
            options={
                'verbose_name': 'Client Price',
                'verbose_name_plural': 'Client Prices',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.price',),
        ),
    ]
