# Generated by Django 5.1.1 on 2024-09-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0004_alter_register_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Register',
                'verbose_name_plural': 'Admin Registration',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.register',),
        ),
    ]
