# Generated by Django 5.1.1 on 2024-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.JSONField(),
        ),
    ]
