# Generated by Django 5.1.1 on 2024-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_register_contact_register_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='coupon_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
