# Generated by Django 5.0.3 on 2024-03-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Price',
                'verbose_name_plural': 'Admin Prices',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.price',),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Schedule',
                'verbose_name_plural': 'Admin Schedules',
                'ordering': ['date_from'],
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.schedule',),
        ),
    ]
